8
Exirel/sopel-8ball pull request #2
Opened 2022-01-19 16:36 UTC by xnaas

8﻿

2022-01-19 16:57 UTC, Exirel requested changes

2022-01-19 16:57 UTC, Exirel commented on sopel_8ball/plugin.py
> +@plugin.commands('8ball', '8')
Make it 8b and we have a deal.

```suggestion
@plugin.commands('8ball', '8b')
```

2022-01-19 17:06 UTC, xnaas commented
I'm not even gonna count this as a compromise. It's a total loss for 8ballers everywhere. 🤪

2022-01-20 16:56 UTC, Exirel commented
So, I've decided to do the things I want myself, adding tests, and I put you as a co-author of the commit. Version 0.3.0 (to be release in a few minutes) will contain the alias.

2022-01-20 16:56 UTC, closed without merging